config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  resources :guests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :attend, presence: true, length: { maximum: 255 }
  validates :allergy, presence: true, length: { maximum: 255 }
  validates :message, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests = Guest.all
  end
  
  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)

    if @message.save
      flash[:success] = 'ご回答ありがとうございました。'
      redirect_to @guest
    else
      flash.now[:danger] = 'エラーが発生しました。'
      render :new
    end
  end

end

  private

  # Strong Parameter
  def guest_params
    params.require(:guest).permit(:name, :address, :email, :attend, :allergy, :message)
  end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest) do |f| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% guest.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <li><%= f.label :name, '名前' %></li>
  <%= f.text_field :name %>
  
  <li><%= f.label :address, '住所' %></li>
  <%= f.text_field :address %>
  
  <li><%= f.label :email, 'メールアドレス' %></li>
  <%= f.text_field :email %>
  
  <li><%= f.label :attend, '出席' %></li>
  <%= f.text_field :attend %>
  
  <li><%= f.label :allergy, 'アレルギー' %></li>
  <%= f.text_field :allergy %>
  
  <li><%= f.label :message, 'メッセージ' %></li>
  <%= f.text_field :message %>

  <li><%= f.submit '送信' %></li>
<% end %>

app/views/guests/confirm.html.erb
<h1>入力内容の確認</h1>

    <li><%= guest.name %></li>
    <li><%= guest.address %></li>
    <li><%= guest.email %></li>
    <li><%= guest.attend %></li>
    <li><%= guest.allergy %></li>
    <li><%= guest.message %></li>
<%= link_to '戻る', guests_path %>

app/views/guests/index.html.erb
<h1>ご回答ありがとうございます。</h1>

<ul>
  <% @guests.each do |guest| %>
    <li><%= guest.name %></li>
    <li><%= guest.address %></li>
    <li><%= guest.email %></li>
    <li><%= guest.attend %></li>
    <li><%= guest.allergy %></li>
    <li><%= guest.message %></li>
  <% end %>
</ul>

<%= link_to '参加確認', new_guest_path %>

app/views/guests/new.html.erb
<%= form_with(model: @guest ) do |f| %>
  <li><%= f.label :name, '名前' %></li>
  <%= f.text_field :name %>
  
  <li><%= f.label :address, '住所' %></li>
  <%= f.text_field :address %>
  
  <li><%= f.label :email, 'メールアドレス' %></li>
  <%= f.text_field :email %>
  
  <li><%= f.label :attend, '出席' %></li>
  <%= f.text_field :attend %>
  
  <li><%= f.label :allergy, 'アレルギー' %></li>
  <%= f.text_field :allergy %>
  
  <li><%= f.label :message, 'メッセージ' %></li>
  <%= f.text_field :message %>

  <li><%= f.submit '送信' %></li>
  <%= link_to '戻る', guests_path %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= guest %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-info">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand text-white" href="/">太郎＆花子</a>
      <!-- 横幅が狭い時に出るハンバーガーボタン -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- メニュー項目 -->
      <div class="collapse navbar-collapse justify-content-flex-start" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="col-md-6 offset-md-3 shadow-lg nav-item"><%= link_to  'our story', new_guest_path, class: 'btn btn-light nav-link' %></li>
          <li class="col-md-6 offset-md-3 shadow-lg nav-item"><%= link_to  'wedding', new_guest_path, class: 'btn btn-light nav-link' %></li>
          <li class="col-md-6 offset-md-3 shadow-lg nav-item"><%= link_to  'gallery', new_guest_path, class: 'btn btn-light nav-link' %></li>
          <li class="col-md-6 offset-md-3 shadow-lg nav-item"><%= link_to  '参加確認', new_guest_path, class: 'btn btn-light nav-link' %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="bg-secondary p-3 p-sm-5 my-4 rounded">
  <div class="text-center text-white">
    <h1>写真</h1>
  </div>
</div>